### ISSUE TITLE
Playlists all picking up the same track and not updating

### ISSUE THREAD

**Issue by jdhodges** [mirrorfm/core#28]
Looks like there's quite a few playlists that are picking up the track "Innisai Paadivarum - Language: Tamil; Film: Thullatha Manamum Thullum; Film Artist 1: Vijay; Film Artist 2: Simran" and have stopped updating with new tracks.

Some examples:
https://open.spotify.com/playlist/3nEA2Y9Q5tYqXmSQ5pk3es?si=f4f04fa2eb464385
https://open.spotify.com/playlist/1LUD1EklEy8lnDrBwJIxca?si=9adb5669f5ca4bc2
https://open.spotify.com/playlist/6JHVqj1hMAu5zuBhcpifil?si=0e27b963e00b46cc

**Comment by stephanebruckert** [comment]
Hey @jdhodges, I didn't write back but yes this is fixed for future tracks, however I'm still working on cleaning up incorrectly added tracks such as "Innisai Paadivarum - Language: Tamil; Film: Thullatha Manamum Thullum; Film Artist 1: Vijay; Film Artist 2: Simran"

Thanks for opening this issue!

**Comment by jdhodges** [comment]
Thanks for fixing, nice one!!!
